"""The Gazebo world, generated from the scenario, never drawn by hand (M5.1).

``caatc/scenario.py`` is the only definition of the road. This module turns a
``ScenarioConfig`` and a set of start poses into a Gazebo world file: a flat ground, the
lane lines as thin flat strips, two low walls a little outside the outer lanes (so a lidar
has something to see), and one ``racecar`` model per agent, named ``car0`` (the emergency
vehicle) to ``car{N-1}``, in the referee's agent order. The referee and the world therefore
use the same numbers, the same rule M4 applied to the observation.

Pure Python: no Gazebo needed to generate or test the file.
"""
from __future__ import annotations

from typing import List, Tuple
from xml.sax.saxutils import escape

import numpy as np

from .frenet import CenterlineFrame
from .scenario import ScenarioConfig, centerline_xy

WORLD_NAME = "clearance"
CAR_Z = 0.05                 # the model origin sits one wheel radius above the ground
WALL_HEIGHT = 0.3
WALL_THICKNESS = 0.1
WALL_MARGIN = 0.6            # m outside the outer lane edge
SEGMENT_M = 0.5              # strips and walls are boxes this long along the road


def car_name(i: int) -> str:
    return f"car{i}"


def _polyline(frame: CenterlineFrame, d: float, seg: float = SEGMENT_M) -> List[Tuple[float, float, float, float]]:
    """Boxes along the road at lateral offset d: (x, y, yaw, length) per segment."""
    n = max(2, int(np.ceil(frame.length / seg)) + 1)
    ss = np.linspace(0.0, frame.length, n)
    pts = np.array([frame.frenet_to_xytheta(s, d)[:2] for s in ss])
    out = []
    for a, b in zip(pts[:-1], pts[1:]):
        mid = (a + b) / 2.0
        dx, dy = b - a
        out.append((float(mid[0]), float(mid[1]), float(np.arctan2(dy, dx)), float(np.hypot(dx, dy)) + 0.02))
    return out


def _strip_model(name: str, boxes, z: float, size_y: float, size_z: float, color: str,
                 collide: bool) -> str:
    vis = []
    for k, (x, y, yaw, length) in enumerate(boxes):
        geom = f"<geometry><box><size>{length:.4f} {size_y} {size_z}</size></box></geometry>"
        pose = f"<pose>{x:.4f} {y:.4f} {z:.4f} 0 0 {yaw:.5f}</pose>"
        vis.append(f'      <visual name="v{k}">{pose}{geom}<material><ambient>{color}</ambient><diffuse>{color}</diffuse></material></visual>')
        if collide:
            vis.append(f'      <collision name="c{k}">{pose}{geom}</collision>')
    body = "\n".join(vis)
    return f'''    <model name="{name}"><static>true</static><link name="l">
{body}
    </link></model>'''


def world_sdf(cfg: ScenarioConfig, poses: np.ndarray, name: str = WORLD_NAME,
              lane_lines: bool = True, walls: bool = True) -> str:
    """The world as SDF text. ``poses`` is (N, 3): x, y, theta per agent, in agent order."""
    poses = np.asarray(poses, dtype=float)
    if poses.shape != (cfg.num_agents, 3):
        raise ValueError(f"poses must be ({cfg.num_agents}, 3), got {poses.shape}")
    frame = CenterlineFrame(*centerline_xy(cfg))
    half = cfg.num_lanes * cfg.lane_width / 2.0
    parts = []
    if lane_lines:
        for i in range(cfg.num_lanes + 1):
            d = (i - cfg.ev_lane - 0.5) * cfg.lane_width
            edge = i in (0, cfg.num_lanes)
            parts.append(_strip_model(f"lane_line_{i}", _polyline(frame, d), 0.001, 0.05 if edge else 0.03, 0.002,
                                      "0.95 0.95 0.95 1" if edge else "0.75 0.75 0.75 1", collide=False))
    if walls:
        for side, d in (("left", half + WALL_MARGIN), ("right", -(half + WALL_MARGIN))):
            parts.append(_strip_model(f"wall_{side}", _polyline(frame, d), WALL_HEIGHT / 2.0, WALL_THICKNESS, WALL_HEIGHT,
                                      "0.6 0.6 0.62 1", collide=True))
    cars = "\n".join(
        f'''    <include>
      <uri>model://racecar</uri>
      <name>{car_name(i)}</name>
      <pose>{poses[i, 0]:.6f} {poses[i, 1]:.6f} {CAR_Z} 0 0 {poses[i, 2]:.6f}</pose>
    </include>''' for i in range(cfg.num_agents))
    gx, gsize = cfg.road_length / 2.0, cfg.road_length + 40.0
    return f'''<?xml version="1.0"?>
<!-- generated by caatc.gazebo_world from the scenario; do not edit by hand -->
<sdf version="1.9">
  <world name="{escape(name)}">
    <physics name="1ms" type="dart"><max_step_size>0.001</max_step_size><real_time_factor>0</real_time_factor></physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors"><render_engine>ogre2</render_engine></plugin>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-contact-system" name="gz::sim::systems::Contact"/>
    <light type="directional" name="sun"><pose>0 0 10 0 0 0</pose><direction>-0.5 0.1 -0.9</direction><diffuse>0.8 0.8 0.8 1</diffuse></light>
    <model name="ground"><static>true</static><pose>{gx:.3f} 0 0 0 0 0</pose><link name="l">
      <collision name="c"><geometry><plane><normal>0 0 1</normal><size>{gsize:.1f} 40</size></plane></geometry>
        <surface><friction><ode><mu>1.0</mu><mu2>1.0</mu2></ode></friction></surface></collision>
      <visual name="v"><geometry><plane><normal>0 0 1</normal><size>{gsize:.1f} 40</size></plane></geometry>
        <material><ambient>0.35 0.35 0.36 1</ambient><diffuse>0.35 0.35 0.36 1</diffuse></material></visual></link></model>
{chr(10).join(parts)}
{cars}
  </world>
</sdf>
'''


def write_world(cfg: ScenarioConfig, poses: np.ndarray, path: str, **kw) -> str:
    with open(path, "w") as f:
        f.write(world_sdf(cfg, poses, **kw))
    return path
